# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  SourDo_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  SourDo_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := SourDo Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

SourDo:
ifneq (,$(SourDo_config))
	@echo "==== Building SourDo ($(SourDo_config)) ===="
	@${MAKE} --no-print-directory -C SourDo -f Makefile config=$(SourDo_config)
endif

Sandbox: SourDo
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C SourDo -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SourDo"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"